export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA';
export const FETCH_PRODUCT_DATA_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_DATA_ERROR = 'FETCH_PRODUCT_ERROR';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

